sonar.projectKey=com.chavaillaz:rsql-jpa-repository
sonar.projectName=RSQL JPA Repository
sonar.organization=chavaillaz
sonar.language=java
sonar.sources=src/main/java/
sonar.java.binaries=target/classes
sonar.java.libraries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=https://sonarcloud.io