name: Databases
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
jobs:
  test:
    name: ${{ matrix.database }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: [ postgresql, sqlserver, oracle ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Test on ${{ matrix.database }}
        run: mvn -B verify -Ddatabase=${{ matrix.database }}
